package QuizMaker.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ConnectConnection = 0;
  public static final int ConnectGame = 1;
  public static final int ConnectQuestion = 2;
  public static final int OneWrongGame = 3;
  public static final int OneWrongQuestion = 4;
  public static final int Question = 5;
  public static final int Quiz = 6;
  public static final int ThreeAnswersQuestion = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L);
    builder.put(0x62308b0ce74d4a35L, ConnectConnection);
    builder.put(0x62308b0ce74d4919L, ConnectGame);
    builder.put(0x62308b0ce74d491eL, ConnectQuestion);
    builder.put(0x5211655e763f1c98L, OneWrongGame);
    builder.put(0x5211655e763f1ca2L, OneWrongQuestion);
    builder.put(0x1127f693adbd6f39L, Question);
    builder.put(0x1127f693adbd6f6eL, Quiz);
    builder.put(0x1127f693adbd6f55L, ThreeAnswersQuestion);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
