package QuizMaker.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptConnectConnection = createDescriptorForConnectConnection();
  /*package*/ final ConceptDescriptor myConceptConnectGame = createDescriptorForConnectGame();
  /*package*/ final ConceptDescriptor myConceptConnectQuestion = createDescriptorForConnectQuestion();
  /*package*/ final ConceptDescriptor myConceptOneWrongGame = createDescriptorForOneWrongGame();
  /*package*/ final ConceptDescriptor myConceptOneWrongQuestion = createDescriptorForOneWrongQuestion();
  /*package*/ final ConceptDescriptor myConceptQuestion = createDescriptorForQuestion();
  /*package*/ final ConceptDescriptor myConceptQuiz = createDescriptorForQuiz();
  /*package*/ final ConceptDescriptor myConceptThreeAnswersQuestion = createDescriptorForThreeAnswersQuestion();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptConnectConnection, myConceptConnectGame, myConceptConnectQuestion, myConceptOneWrongGame, myConceptOneWrongQuestion, myConceptQuestion, myConceptQuiz, myConceptThreeAnswersQuestion);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ConnectConnection:
        return myConceptConnectConnection;
      case LanguageConceptSwitch.ConnectGame:
        return myConceptConnectGame;
      case LanguageConceptSwitch.ConnectQuestion:
        return myConceptConnectQuestion;
      case LanguageConceptSwitch.OneWrongGame:
        return myConceptOneWrongGame;
      case LanguageConceptSwitch.OneWrongQuestion:
        return myConceptOneWrongQuestion;
      case LanguageConceptSwitch.Question:
        return myConceptQuestion;
      case LanguageConceptSwitch.Quiz:
        return myConceptQuiz;
      case LanguageConceptSwitch.ThreeAnswersQuestion:
        return myConceptThreeAnswersQuestion;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForConnectConnection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "ConnectConnection", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4a35L);
    b.class_(false, false, false);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/7075307902135519797");
    b.version(2);
    b.property("firstNode", 0x62308b0ce74d4a38L).type(PrimitiveTypeId.STRING).origin("7075307902135519800").done();
    b.property("secondNode", 0x62308b0ce74d4a3aL).type(PrimitiveTypeId.STRING).origin("7075307902135519802").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConnectGame() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "ConnectGame", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4919L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/7075307902135519513");
    b.version(2);
    b.aggregate("connectQuestions", 0x62308b0ce74d491fL).target(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d491eL).optional(true).ordered(true).multiple(true).origin("7075307902135519519").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConnectQuestion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "ConnectQuestion", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d491eL);
    b.class_(false, false, false);
    b.super_("QuizMaker.structure.Question", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f39L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/7075307902135519518");
    b.version(2);
    b.aggregate("connection", 0x62308b0ce74f89caL).target(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4a35L).optional(false).ordered(true).multiple(true).origin("7075307902135667146").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOneWrongGame() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "OneWrongGame", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1c98L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/5913619242099350680");
    b.version(2);
    b.aggregate("oneWrongQuestions", 0x5211655e763f1ca3L).target(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L).optional(true).ordered(true).multiple(true).origin("5913619242099350691").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOneWrongQuestion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "OneWrongQuestion", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L);
    b.class_(false, false, false);
    b.super_("QuizMaker.structure.Question", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f39L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/5913619242099350690");
    b.version(2);
    b.property("wrong", 0x5211655e763f1ca5L).type(PrimitiveTypeId.STRING).origin("5913619242099350693").done();
    b.property("correctOne", 0x5211655e763f1ca7L).type(PrimitiveTypeId.STRING).origin("5913619242099350695").done();
    b.property("correctTwo", 0x5211655e763f1caaL).type(PrimitiveTypeId.STRING).origin("5913619242099350698").done();
    b.property("correctThree", 0x5211655e763f1caeL).type(PrimitiveTypeId.STRING).origin("5913619242099350702").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuestion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "Question", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f39L);
    b.class_(false, true, false);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/1236227736871989049");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuiz() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "Quiz", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f6eL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/1236227736871989102");
    b.version(2);
    b.aggregate("questions", 0x1127f693adbd6f71L).target(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f39L).optional(true).ordered(true).multiple(true).origin("1236227736871989105").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForThreeAnswersQuestion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("QuizMaker", "ThreeAnswersQuestion", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L);
    b.class_(false, false, false);
    b.super_("QuizMaker.structure.Question", 0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f39L);
    b.origin("r:89548611-525a-4e43-9250-b4d78c65413c(QuizMaker.structure)/1236227736871989077");
    b.version(2);
    b.property("question", 0x1127f693adbd6f56L).type(PrimitiveTypeId.STRING).origin("1236227736871989078").done();
    b.property("correctAnswer", 0x1127f693adbd6f58L).type(PrimitiveTypeId.STRING).origin("1236227736871989080").done();
    b.property("firstFalseAnswer", 0x1127f693adbd6f5bL).type(PrimitiveTypeId.STRING).origin("1236227736871989083").done();
    b.property("secondFalseAnswer", 0x1127f693adbd6f5fL).type(PrimitiveTypeId.STRING).origin("1236227736871989087").done();
    b.alias("threeAnswerQuestion");
    return b.create();
  }
}
