package QuizMaker.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ConnectConnection_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ConnectGame_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ConnectQuestion_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new OneWrongGame_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new OneWrongQuestion_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Quiz_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new ThreeAnswersQuestion_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4a35L), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4919L), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d491eL), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1c98L), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f6eL), MetaIdFactory.conceptId(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L)).seal();
}
