package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1);
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.question$XHg0);
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.correctAnswer$XHr9);
  }
  public static Object propertyMacro_GetValue_2_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.firstFalseAnswer$XHsA);
  }
  public static Object propertyMacro_GetValue_2_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.secondFalseAnswer$XHuy);
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1);
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.wrong$SJbY);
  }
  public static Object propertyMacro_GetValue_4_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.correctOne$SJcW);
  }
  public static Object propertyMacro_GetValue_4_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.correctTwo$SJep);
  }
  public static Object propertyMacro_GetValue_4_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.correctThree$SOlP);
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$tAp1);
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.firstNode$N5fu);
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.secondNode$N5gs);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.questions$XN2u);
  }
  public static Iterable<SNode> sourceNodesQuery_3_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.oneWrongQuestions$SJax);
  }
  public static Iterable<SNode> sourceNodesQuery_5_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.connectQuestions$MJcr);
  }
  public static Iterable<SNode> sourceNodesQuery_6_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.connection$6Rf$);
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("1236227736873897133", new SNsQ(i++));
    snsqMethods.put("5913619242100593274", new SNsQ(i++));
    snsqMethods.put("7075307902137153845", new SNsQ(i++));
    snsqMethods.put("7075307902138247676", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_0(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_0(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("7075307902136341617", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_Game"));
    pvqMethods.put("1236227736873850670", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Klausimas?"));
    pvqMethods.put("1236227736873851418", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Atsakymas"));
    pvqMethods.put("1236227736873851750", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Neteisingas"));
    pvqMethods.put("1236227736873852116", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "neteisingas"));
    pvqMethods.put("2223540045889394732", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_OneWrongGame"));
    pvqMethods.put("5913619242103206591", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "no"));
    pvqMethods.put("5913619242103207344", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "yes"));
    pvqMethods.put("5913619242103207677", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "yes"));
    pvqMethods.put("5913619242103208044", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "yes"));
    pvqMethods.put("7075307902136332937", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "map_ConnectGame"));
    pvqMethods.put("7075307902140315769", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "aa"));
    pvqMethods.put("7075307902140316910", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "bb"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_2_1(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_2_2(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_2_3(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_4_1(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_4_2(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_4_3(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$tAp1 = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty question$XHg0 = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L, 0x1127f693adbd6f56L, "question");
    /*package*/ static final SProperty correctAnswer$XHr9 = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L, 0x1127f693adbd6f58L, "correctAnswer");
    /*package*/ static final SProperty firstFalseAnswer$XHsA = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L, 0x1127f693adbd6f5bL, "firstFalseAnswer");
    /*package*/ static final SProperty secondFalseAnswer$XHuy = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f55L, 0x1127f693adbd6f5fL, "secondFalseAnswer");
    /*package*/ static final SProperty wrong$SJbY = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L, 0x5211655e763f1ca5L, "wrong");
    /*package*/ static final SProperty correctOne$SJcW = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L, 0x5211655e763f1ca7L, "correctOne");
    /*package*/ static final SProperty correctTwo$SJep = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L, 0x5211655e763f1caaL, "correctTwo");
    /*package*/ static final SProperty correctThree$SOlP = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1ca2L, 0x5211655e763f1caeL, "correctThree");
    /*package*/ static final SProperty firstNode$N5fu = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4a35L, 0x62308b0ce74d4a38L, "firstNode");
    /*package*/ static final SProperty secondNode$N5gs = MetaAdapterFactory.getProperty(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4a35L, 0x62308b0ce74d4a3aL, "secondNode");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink questions$XN2u = MetaAdapterFactory.getContainmentLink(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x1127f693adbd6f6eL, 0x1127f693adbd6f71L, "questions");
    /*package*/ static final SContainmentLink oneWrongQuestions$SJax = MetaAdapterFactory.getContainmentLink(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x5211655e763f1c98L, 0x5211655e763f1ca3L, "oneWrongQuestions");
    /*package*/ static final SContainmentLink connectQuestions$MJcr = MetaAdapterFactory.getContainmentLink(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d4919L, 0x62308b0ce74d491fL, "connectQuestions");
    /*package*/ static final SContainmentLink connection$6Rf$ = MetaAdapterFactory.getContainmentLink(0xb4230d9144a04bafL, 0x9497009e9bc63ab0L, 0x62308b0ce74d491eL, 0x62308b0ce74f89caL, "connection");
  }
}
